# Generated by Django 2.2.1 on 2019-05-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목을 입력하세요.', max_length=200)),
                ('content', models.TextField()),
                ('img', models.FileField(null=True, upload_to='')),
                ('author', models.CharField(default='', max_length=50)),
                ('menu', models.CharField(choices=[('pizza', '피자'), ('chicken', '치킨'), ('bossam', '보쌈'), ('tteok', '떡볶이'), ('jok', '족발'), ('dak', '닭발'), ('sap', '삽겹살'), ('mara', '마라샹궈'), ('jjim', '찜닭')], max_length=30)),
                ('school', models.CharField(choices=[('KU', '고려대학교'), ('Yonsei', '연세대학교'), ('SeongShin', '성신여대')], max_length=30)),
                ('kp', models.CharField(choices=[('KU', '고려대 CU'), ('KU', '고려대 GS25'), ('KU', '고려대 미니스톱')], max_length=30)),
                ('yp', models.CharField(choices=[('Yonsei', '연세 CU'), ('Yonsei', '연세 GS25'), ('Yonsei', '연세 미니스톱')], max_length=30)),
                ('sp', models.CharField(choices=[('SeongShin', '성신 CU'), ('SeongShin', '성신 GS25'), ('SeongShin', '성신 미니스톱')], max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='bbom.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bbom.Post')),
            ],
        ),
    ]
