# Generated by Django 2.2.1 on 2019-05-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='timeSet',
        ),
    ]
