# Generated by Django 2.1.7 on 2019-05-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbom', '0002_add_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
